name: Build Armbian Image fo oLinuXino Lime A20 board
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: armbian/build@main
        with:
          armbian_token: ${{ secrets.GITHUB_TOKEN }}
          armbian_board: lime
          armbian_release: trixie
          armbian_target: build
          armbian_ui: minimal
          armbian_runner_clean: "yes"
